### ISSUE TITLE
Compile error. 

### ISSUE THREAD

**Issue by str1der** [mikaelpatel/Arduino-RTC#1]
Arduino: 1.8.4 (Windows 10), Board: "Arduino/Genuino Uno"

C:\Users\fkarakutuk\Documents\Arduino\libraries\Arduino-RTC-master\examples\RTC\RTC.ino:16:17: fatal error: TWI.h: No such file or directory

 #include "TWI.h"

                 ^

compilation terminated.

exit status 1
Error compiling for board Arduino/Genuino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by mikaelpatel** [comment]
The TWI library requires two other libraries; [Arduino-GPIO](https://github.com/mikaelpatel/Arduino-GPIO) and [Arduino-TWI](https://github.com/mikaelpatel/Arduino-TWI). Please download and install them.
